#!/bin/bash

# CarniTrack Edge - .env File Generator (Shell Script)
# 
# Simple shell script version that generates a .env.example template
# 
# Usage:
#   ./scripts/create-env.sh              # Generate .env.example
#   ./scripts/create-env.sh .env         # Generate .env file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="${1:-$PROJECT_ROOT/.env.example}"

cat > "$OUTPUT_FILE" << 'EOF'
# ═══════════════════════════════════════════════════════════════════════════════
# CarniTrack Edge - Environment Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# Generated by: scripts/create-env.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# This file contains all configurable environment variables.
# Uncomment and set values as needed. Defaults are shown.
#
# To generate this file interactively, run: bun scripts/create-env.ts
#

# ───────────────────────────────────────────────────────────────────────────────
# Edge Identity
# ───────────────────────────────────────────────────────────────────────────────
# Edge device name (human-readable identifier for this Edge instance, used as site name if provided)
EDGE_NAME=

# Site ID for registration (from Cloud setup) (REQUIRED)
SITE_ID=

# Site registration token (for initial Cloud registration) (REQUIRED)
REGISTRATION_TOKEN=

# ───────────────────────────────────────────────────────────────────────────────
# TCP Server
# ───────────────────────────────────────────────────────────────────────────────
# Port to listen for scale connections
TCP_PORT=8899

# Host to bind TCP server (0.0.0.0 for all interfaces)
TCP_HOST=0.0.0.0

# ───────────────────────────────────────────────────────────────────────────────
# HTTP Server
# ───────────────────────────────────────────────────────────────────────────────
# Port for admin dashboard and API
HTTP_PORT=3000

# Host to bind HTTP server
HTTP_HOST=0.0.0.0

# ───────────────────────────────────────────────────────────────────────────────
# Database
# ───────────────────────────────────────────────────────────────────────────────
# Path to SQLite database file (relative to project root)
DB_PATH=data/carnitrack.db

# ───────────────────────────────────────────────────────────────────────────────
# Cloud Connection
# ───────────────────────────────────────────────────────────────────────────────
# Cloud API base URL
CLOUD_API_URL=https://api.carnitrack.com/api/v1/edge

# Session polling interval (ms)
SESSION_POLL_INTERVAL_MS=5000

# Event POST timeout (ms)
EVENT_SEND_TIMEOUT_MS=10000

# Max retry attempts for failed requests
REST_MAX_RETRIES=3

# Initial retry delay (ms)
REST_RETRY_DELAY_MS=1000

# Retry backoff multiplier
REST_BACKOFF_MULTIPLIER=2

# Maximum retry delay (ms)
REST_MAX_RETRY_DELAY_MS=30000

# Batch size for event uploads
CLOUD_BATCH_SIZE=50

# Batch interval for pending events (ms)
BATCH_INTERVAL_MS=5000

# ───────────────────────────────────────────────────────────────────────────────
# Health Monitoring
# ───────────────────────────────────────────────────────────────────────────────
# Time without heartbeat before marking device disconnected (ms) - 2 missed HBs
HEARTBEAT_TIMEOUT_MS=60000

# ───────────────────────────────────────────────────────────────────────────────
# Activity Monitoring
# ───────────────────────────────────────────────────────────────────────────────
# Time without weight events before marking device 'idle' (ms) - 5 minutes
ACTIVITY_IDLE_MS=300000

# Time without weight events before marking device 'stale' (ms) - 30 minutes
ACTIVITY_STALE_MS=1800000

# ───────────────────────────────────────────────────────────────────────────────
# Session Cache
# ───────────────────────────────────────────────────────────────────────────────
# How long to keep cached session valid without Cloud update (ms) - 4 hours
SESSION_CACHE_EXPIRY_MS=14400000

# ───────────────────────────────────────────────────────────────────────────────
# Offline Mode
# ───────────────────────────────────────────────────────────────────────────────
# Time without Cloud connection before entering offline mode (ms)
OFFLINE_TRIGGER_DELAY_MS=5000

# Maximum events to store per offline batch before starting new batch
OFFLINE_MAX_EVENTS_PER_BATCH=1000

# How long to keep offline batches before cleanup (days)
OFFLINE_BATCH_RETENTION_DAYS=30

# ───────────────────────────────────────────────────────────────────────────────
# PLU Generation
# ───────────────────────────────────────────────────────────────────────────────
# Output directory for generated PLU files (relative to project root)
PLU_OUTPUT_DIR=generated

# ───────────────────────────────────────────────────────────────────────────────
# Work Hours
# ───────────────────────────────────────────────────────────────────────────────
# Work start time (HH:MM)
WORK_HOURS_START=06:00

# Work end time (HH:MM)
WORK_HOURS_END=18:00

# Timezone
TIMEZONE=Europe/Istanbul

# ───────────────────────────────────────────────────────────────────────────────
# Logging
# ───────────────────────────────────────────────────────────────────────────────
# Log level: debug, info, warn, error
LOG_LEVEL=info

# Log directory (relative to project root)
LOG_DIR=logs
EOF

# Replace the date placeholder
if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  sed -i '' "s/\$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/" "$OUTPUT_FILE"
else
  # Linux
  sed -i "s/\$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/" "$OUTPUT_FILE"
fi

echo "✓ Generated .env file at: $OUTPUT_FILE"
echo ""
echo "⚠️  Don't forget to set the required fields:"
echo "   - SITE_ID"
echo "   - REGISTRATION_TOKEN"
echo ""
echo "For interactive configuration, run: bun scripts/create-env.ts"
